### ISSUE TITLE
expl3 macros only available in LaTeX format

### ISSUE THREAD

**Issue by muzimuzhi** [T-F-S/tikzfill#1]
The doc implies `tikzfill` libraries are usable in each of plain TeX, LaTeX, and ConTeXt formats.
https://github.com/T-F-S/tikzfill/blob/899c3ff0dde52f72d1e16f1520fa8b38f7b506b0/doc/latex/tikzfill/tikzfill.tex#L146-L152
But that's not true because currently all three libraries uses `expl3` functions but only LaTeX format is shipped with `expl3`.

To use `expl3` macros in portable ways, perhaps `tikzfill` could load the generic loader `expl3-generic.tex`, as suggested in `texdoc expl3`, sec. 8 "Using expl3 with formats other than LaTeX2ε". Writing `\input expl3-generic ` in LaTeX is safe as well.

Also personally, in plain text `plain TeX, LaTeX, and ConTeXt` is preferable than the all-uppercase `TEX, LATEX, and ConTEXt`.

**Comment by T-F-S** [comment]
> To use `expl3` macros in portable ways, perhaps `tikzfill` could load the generic loader `expl3-generic.tex`, as suggested in `texdoc expl3`, sec. 8 "Using expl3 with formats other than LaTeX2ε". Writing `\input expl3-generic ` in LaTeX is safe as well.

I just checked that only six packages use `\input expl3-generic ` and only two use it directly. The others have safe-guards where

```latex
\ifx\ExplSyntaxOn\undefined
  \input expl3-generic\relax
\fi
```

seems the simplest one to me.

On the other hand, one could argue that a `tikzlibrary` does not work by itself. It needs TikZ which is not loaded by the library. From a philosophical point of view I would not like a library to load *all expl3*, if it does not load *all TikZ* ...
But, of course, the lines above would not hurt much... Or I add a hint in the documentation that expl3 support has to be present (?).

Finally: I will add these lines to the libraries since they provide no overhead.

**Comment by T-F-S** [comment]
> Also personally, in plain text `plain TeX, LaTeX, and ConTeXt` is preferable than the all-uppercase `TEX, LATEX, and ConTEXt`.

That was copy-and-paste from the `pgfmanual.pdf`. I agree that one should write it as you did.

**Comment by muzimuzhi** [comment]
> From a philosophical point of view I would not like a library to load _all expl3_, if it does not load _all TikZ_ ...

expl3 doesn't provide a library/module mechanism, while tikz does. Hence a third-party expl3 module is usually in the form of a separate LaTeX package, while extensions to tikz have two choices, either as a standalone LaTeX package or as one of tikz's libraries. And as a tikz library it gains the same portability as tikz has (assume the implementation is portable as well).

Therefore I think the difference between loading all expl3 and only needed part of tikz is ok and (more or less) by design.

**Comment by T-F-S** [comment]
Done with https://github.com/T-F-S/tikzfill/releases/tag/v1.0.1
