### ISSUE TITLE
\usepackage{tikzfill} clash to tcolorbox

### ISSUE THREAD

**Issue by yuishin-kikuchi** [T-F-S/tikzfill#2]
```
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{skins}% <--
\usepackage{tikzfill}% <--

\begin{document}
TEST
\end{document}
```

Compilation fails when skins library of tcolorbox loaded.
I know \usetikzlibrary{fill.image} is safe.

**Comment by muzimuzhi** [comment]
The package forms (`tikzfill.sty` and all other `tikzfill-xxx.sty`) load `tikzfill` libraries in expl3 mode, i.e., inside `\ExplSyntaxOn ... \ExplSyntaxOff`.
https://github.com/T-F-S/tikzfill/blob/7d03f742686ff35effdc018cd9013e907bfef933/tex/latex/tikzfill/tikzfill.sty#L22-L24
When one of these libraries then loads (built-in) tikz library, such library is also loaded in expl3 mode, which is not supported. For example, `fill.hexagon` library in `tikzfill` loads `patterns.meta`.
https://github.com/T-F-S/tikzfill/blob/7d03f742686ff35effdc018cd9013e907bfef933/tex/latex/tikzfill/tikzlibraryfill.hexagon.code.tex#L22

**Comment by muzimuzhi** [comment]
IMO, it's better to always load `tikzfill` libraries in non-expl3 mode (either normal category codes or LaTeX2e internal category codes).

Apart from using `\@usename{__tikzfill_usetikzlibrary:n}` or renaming it to for example `\tikzfill@usetikzlibrary`, I also wonder why there's the need for `\__tikzfill_usetikzlibrary:n`, since tikz already provides `\usetikzlibrary`.

**Comment by T-F-S** [comment]
> Apart from using `\@usename{__tikzfill_usetikzlibrary:n}` or renaming it to for example `\tikzfill@usetikzlibrary`, I also wonder why there's the need for `\__tikzfill_usetikzlibrary:n`, since tikz already provides `\usetikzlibrary`.

The reason is that `\usetikzlibrary` does not allow local path prefixes like `\usetikzlibrary{../mytest/mylibrary}`. I use such prefixes in my development environment.

I see the problems with the current loading implementation which somehow did not appear with my tests setups. So, I will throw away the expl3 mode implementation and replace it by some adapted copy of the TikZ loading.

**Comment by T-F-S** [comment]
Fixed with https://github.com/T-F-S/tikzfill/releases/tag/v1.0.1
